### ISSUE TITLE
How to get camera.pkl for SnapshotPeople

### ISSUE THREAD

**Issue by david-svitov** [mikeqzy/3dgs-avatar-release#1]
Hello! I want to launch rendering for SnapshotPeople, but I get this error:
`FileNotFoundError: [Errno 2] No such file or directory: '../../data/peoplesnapshot_arah-format/people_snapshot_public/female-3-casual/camera.pkl'`

As I understand it, camera.pkl can be generated with ARAH code. But they don't have a script for SnapshotPeople. Could you please share your preprocessing script?

**Comment by zhao-yiqun** [comment]
Hi @david-svitov @mikeqzy  

I also do not know how to get these camera.pkl from ARAH code(this is not released).  Could you please share your preprocessing script?

**Comment by david-svitov** [comment]
@zhao-yiqun  They meant the usual camera.pkl from the SnapshotPeople dataset. Download the original dataset, it is there.
