### ISSUE TITLE
wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)

### ISSUE THREAD

**Issue by WangPu1999** [mikeqzy/3dgs-avatar-release#10]
```
wandb: Currently logged in as: wangpu19990606. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
Problem at: train.py 310 main
Error executing job with overrides: ['dataset=zjumocap_377_mono']
Traceback (most recent call last):
  File "train.py", line 310, in main
    wandb.init(
  File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
    raise e
  File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
```
I am a Chinese student and our  school’s server cannot connect to the external network. How can I modify the file to bypass wandb for training?

**Comment by yahui-lee** [comment]
delete "entity='fast avatar'" in the wandb. init() function, maybe this can help you

**Comment by yahui-lee** [comment]
> ```
> wandb: Currently logged in as: wangpu19990606. Use `wandb login --relogin` to force relogin
> wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
> Problem at: train.py 310 main
> Error executing job with overrides: ['dataset=zjumocap_377_mono']
> Traceback (most recent call last):
>   File "train.py", line 310, in main
>     wandb.init(
>   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
>     raise e
>   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
>     run = wi.init()
>   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
>     raise error
> wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
> ```
> 
> I am a Chinese student and our school’s server cannot connect to the external network. How can I modify the file to bypass wandb for training?

delete "entity='fast avatar'" in the wandb. init() function, maybe this can help you

**Comment by mikeqzy** [comment]
You can add "mode='disabled'" in wandb.init() to completely disable wandb logging.

**Comment by WangPu1999** [comment]
> > ```
> > wandb: Currently logged in as: wangpu19990606. Use `wandb login --relogin` to force relogin
> > wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
> > Problem at: train.py 310 main
> > Error executing job with overrides: ['dataset=zjumocap_377_mono']
> > Traceback (most recent call last):
> >   File "train.py", line 310, in main
> >     wandb.init(
> >   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
> >     raise e
> >   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
> >     run = wi.init()
> >   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
> >     raise error
> > wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am a Chinese student and our school’s server cannot connect to the external network. How can I modify the file to bypass wandb for training?
> 
> delete "entity='fast avatar'" in the wandb. init() function, maybe this can help you

Thank you very very very much🥰! The problem mentioned above is solved by deleting "entity='fast avatar'" bur another problem occurs (the numpy version is too high the do not support the "np.float")🥲, i am trying to solve the new problem.

**Comment by JasperPWang** [comment]
> > ```
> > wandb: Currently logged in as: wangpu19990606. Use `wandb login --relogin` to force relogin
> > wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
> > Problem at: train.py 310 main
> > Error executing job with overrides: ['dataset=zjumocap_377_mono']
> > Traceback (most recent call last):
> >   File "train.py", line 310, in main
> >     wandb.init(
> >   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
> >     raise e
> >   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
> >     run = wi.init()
> >   File "/home/wangpu/anaconda3/envs/3dgs-avatar/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
> >     raise error
> > wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am a Chinese student and our school’s server cannot connect to the external network. How can I modify the file to bypass wandb for training?
> 
> delete "entity='fast avatar'" in the wandb. init() function, maybe this can help you

Thank you very very very much🥰! The problem mentioned above is solved by deleting "entity='fast avatar'" bur another problem occurs (the numpy version is too high the do not support the "np.float")🥲, i am trying to solve the new problem.

**Comment by JasperPWang** [comment]
> You can add "mode='disabled'" in wandb.init() to completely disable wandb logging.

Thank you for your amazing project (the performence of your project is the best among the open source code at present) , but adding "mode='disabled'" does not work😔.
