### ISSUE TITLE
ModuleNotFoundError: No module named 'im2mesh.utils.libmesh.triangle_hash'

### ISSUE THREAD

**Issue by ImmaFake** [mikeqzy/3dgs-avatar-release#14]
When I want to run the test.py as the readme says. The error above happens. It seems like there is a triangle_hash.pyx in libmesh which is a cython file. What should I do to run the test successfully? Thanks a lot.

**Comment by mikeqzy** [comment]
Hi, it seems like you are running the [ARAH](https://github.com/taconite/arah-release/tree/main/im2mesh/utils/libmesh) code.
