### ISSUE TITLE
Poor performance when training the custom dataset

### ISSUE THREAD

**Issue by yahui-lee** [mikeqzy/3dgs-avatar-release#15]
Thank you very much for your great work. After using the custom dataset (16 cameras and 450 frames, download from another repository named GPS-Gaussian) to extract SMPL parameters, training with the project code did not get satisfactory results (as shown in the following figure). However, using the ZJU-MoCap dataset to extract SMPL parameters using the same method and training, the results were acceptable. Is there a solution to this situation?
![image](https://github.com/mikeqzy/3dgs-avatar-release/assets/102016664/a3405431-e604-42dc-bbb5-85d8126a779e)
![image](https://github.com/mikeqzy/3dgs-avatar-release/assets/102016664/f7f84ea7-e1ee-4854-800b-8dbe5214d0dd)
![image](https://github.com/mikeqzy/3dgs-avatar-release/assets/102016664/fadccde2-4853-43df-b207-e81698021ed2)

**Comment by jiangguangan** [comment]
请问如何制作自己的数据集？

**Comment by mikeqzy** [comment]
Hi, to me it looks like the non-rigid deformation module is not working properly, could you check if the weight is updated?

**Comment by alasokolova** [comment]
Hi @yahui-lee 
Can you please explain, how you processed your custom data to run 3dgs avatar?
