### ISSUE TITLE
How to improve the speed of Test on out of distribution positions

### ISSUE THREAD

**Issue by yahui-lee** [mikeqzy/3dgs-avatar-release#19]
Thank you very much for your great work. currently, I have achieved training and inference on my own dataset. But I found that in terms of inferencing, the speed cannot reach the theoretical 50fps mentioned in your paper. How should I implement it?(By the way, after optimizing the modules outside of the rendering module, the inference speed is approximately 9fps)

**Comment by DarcyFan** [comment]
> Thank you very much for your great work. currently, I have achieved training and inference on my own dataset. But I found that in terms of inferencing, the speed cannot reach the theoretical 50fps mentioned in your paper. How should I implement it?(By the way, after optimizing the modules outside of the rendering module, the inference speed is approximately 9fps)

Hello, Can I ask you which link you installed the simple-knn module from? The simple-knn link appears to be broken under the path submodules/simple-knn

**Comment by mikeqzy** [comment]
> Thank you very much for your great work. currently, I have achieved training and inference on my own dataset. But I found that in terms of inferencing, the speed cannot reach the theoretical 50fps mentioned in your paper. How should I implement it?(By the way, after optimizing the modules outside of the rendering module, the inference speed is approximately 9fps)

Hi, thank you for your interest in our work. Theoretically, the inference runtime would not differ between training poses and out-of-distribution poses, and it is related to your hardware environment (GPU model for instance). Also, depending on your custom dataset, there might be larger number of Gaussian primitives that slow down the inference speed. May I ask if it reaches 50fps on ZJU-MoCap under default config?

**Comment by mikeqzy** [comment]
> > Thank you very much for your great work. currently, I have achieved training and inference on my own dataset. But I found that in terms of inferencing, the speed cannot reach the theoretical 50fps mentioned in your paper. How should I implement it?(By the way, after optimizing the modules outside of the rendering module, the inference speed is approximately 9fps)
> 
> Hello, Can I ask you which link you installed the simple-knn module from? The simple-knn link appears to be broken under the path submodules/simple-knn

Hi, the simple-knn link is from gitlab so it cannot be directly opened from github. But it can be installed by `pip install submodules/simple-knn`
