### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by Tiandishihua** [mikeqzy/3dgs-avatar-release#2]
Can we use the video we shoot?

**Comment by mikeqzy** [comment]
Hi,
In priciple our method can also work on self-captured videos, given that accurate subject masks, SMPL estimation and camera calibration are available. We do not test on such data ourselves, but you can check [HumanNeRF](https://github.com/chungyiweng/humannerf?tab=readme-ov-file#run-on-a-custom-monocular-video) as reference.
