### ISSUE TITLE
Slightly lower performance than the paper

### ISSUE THREAD

**Issue by JuewenPeng** [mikeqzy/3dgs-avatar-release#20]
I have evaluated the pretrained model on the scene 377 of ZJU-MoCap using your code. The PSNR and LPIPS are consistent with the paper, but the SSIM is 0.96977, which is lower than 0.9774 reported in the paper.

**Comment by mikeqzy** [comment]
Hi, this is weird, did you use the evaluation code [here](https://github.com/mikeqzy/3dgs-avatar-release/blob/6f57deb6fbd3ad929ce81ab61da8c4e056a5cedd/utils/general_utils.py#L253)? SSIM value could be inconsistent between implementations.

**Comment by JuewenPeng** [comment]
I have fixed this problem by adjusting the version of "skimage" package (0.23.2 -> 0.19.3). Thank you very much.
