### ISSUE TITLE
Evaluation details on PeopleSnapshot dataset.

### ISSUE THREAD

**Issue by GostInShell** [mikeqzy/3dgs-avatar-release#21]
Hi! @mikeqzy  Thank you for contributing the code of your excellent work! I also have several questions regarding the details to achieve the reported results on the Peoplesnapshot dataset.

1. For testing, do you also optimize the poses as InstantAvatar?
2. Are the results obtained using white background?
3. Do you use the latent code of the last training frame as the input of the texture MLP for all testing poses?

**Comment by mikeqzy** [comment]
Hi, many thanks for your interest on our work. Here are the answers:
1. No. InstantAvatar does not optimize the poses:
> We train our model with the pose parameters optimized by Anim-NeRF and keep them frozen throughout training for a fair comparison.

To align with InstantAvatar we also use Anim-NeRF pose and turn off pose optimization. The Anim-NeRF SMPL parameters can be found in README.
2. No, background is black, again it's consistent with InstantAvatar.
3. Yes.
Hope it helps
