### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by IceFtv** [mikeqzy/3dgs-avatar-release#22]
Very Nice Work! But when I run:
python train.py dataset=ps_female_3 option=iter30k pose_correction=none
I got this problem:
![image](https://github.com/mikeqzy/3dgs-avatar-release/assets/117157532/592ef5c9-e74a-472d-b0eb-71be0f77268e)
I am using an A800 with 80GB GPU memory. Normally, this is sufficient. Could you tell me what's wrong?  Thank you very much.

**Comment by yahui-lee** [comment]
I encountered the same issue when I used the A800 for training. However, when I switched to the RTX 3090, the issue didn't occur anymore.

**Comment by mikeqzy** [comment]
Hi,
This seems like a cuda-related bug of the `distCUDA2` function. I would suggest simply switching to lower-end GPUs since our method is not GPU memory demanding.
