### ISSUE TITLE
Error when running ZJU-refine dataset

### ISSUE THREAD

**Issue by soslsos16** [mikeqzy/3dgs-avatar-release#24]
Traceback (most recent call last):
  File "train.py", line 327, in main
    training(config)
  File "train.py", line 68, in training
    scene = Scene(config, gaussians, config.exp_dir)
  File "/root/autodl-tmp/3dgs-avatar-release/scene/__init__.py", line 32, in __init__
    self.train_dataset = load_dataset(cfg.dataset, split='train')
  File "/root/autodl-tmp/3dgs-avatar-release/dataset/__init__.py", line 9, in load_dataset
    return dataset_dict[cfg.name](cfg, split)
  File "/root/autodl-tmp/3dgs-avatar-release/dataset/zjumocap.py", line 58, in __init__
    with open(os.path.join(self.root_dir, self.subject, 'cam_params.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/autodl-tmp/3dgs-avatar-release/data/zjumocap/CoreView_377/cam_params.json'

I downloaded the ZJU-refine dataset from the Instant-nvr project, named my_377, and it shows missing modules when running

**Comment by mikeqzy** [comment]
Hi, please follow [here](https://github.com/taconite/arah-release/blob/main/preprocess_datasets/preprocess_ZJU-MoCap.py) to preprocess the dataset first.

**Comment by soslsos16** [comment]
Thanks for your reply,but someone said that ZJU-refine dataset can run without preprocess(frome previous comments)

**Comment by haowang020110** [comment]
> Hi, please follow [here](https://github.com/taconite/arah-release/blob/main/preprocess_datasets/preprocess_ZJU-MoCap.py) to preprocess the dataset first.

hi,it's seemed that this script is used for processing zju_mocap not zju_mocap_refine

**Comment by mikeqzy** [comment]
> > Hi, please follow [here](https://github.com/taconite/arah-release/blob/main/preprocess_datasets/preprocess_ZJU-MoCap.py) to preprocess the dataset first.
> 
> hi,it's seemed that this script is used for processing zju_mocap not zju_mocap_refine

They share the same structure so you can easily adapt the script to change the filepath

**Comment by radiant123456789** [comment]
> Traceback (most recent call last): File "train.py", line 327, in main training(config) File "train.py", line 68, in training scene = Scene(config, gaussians, config.exp_dir) File "/root/autodl-tmp/3dgs-avatar-release/scene/**init**.py", line 32, in **init** self.train_dataset = load_dataset(cfg.dataset, split='train') File "/root/autodl-tmp/3dgs-avatar-release/dataset/**init**.py", line 9, in load_dataset return dataset_dict[cfg.name](cfg, split) File "/root/autodl-tmp/3dgs-avatar-release/dataset/zjumocap.py", line 58, in **init** 文件 "/root/autodl-tmp/3dgs-avatar-release/dataset/zjumocap.py"，第 58 行，在 init 中 with open(os.path.join(self.root_dir, self.subject, 'cam_params.json'), 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: '/autodl-tmp/3dgs-avatar-release/data/zjumocap/CoreView_377/cam_params.json' FileNotFoundError: [Errno 2] 找不到文件或目录: '/autodl-tmp/3dgs-avatar-release/data/zjumocap/CoreView_377/cam_params.json'
> 
> I downloaded the ZJU-refine dataset from the Instant-nvr project, named my_377, and it shows missing modules when running我从 Instant-nvr 项目中下载了 ZJU-refine 数据集，命名为 my_377，运行时显示缺少模块

你好，你现在能在ZJU-refine 数据集上成功运行了吗
