### ISSUE TITLE
Custom dataset requirements

### ISSUE THREAD

**Issue by agelosk** [mikeqzy/3dgs-avatar-release#25]
Hello and thank you for your work.

I am trying to run your method in a custom dataset and I am trying to see what is the minimum data requirements. Given a dataset structurally similar to ZJU-MoCap your method can run on it directly after this [preprocess script](https://github.com/taconite/arah-release/blob/main/preprocess_datasets/preprocess_ZJU-MoCap.py). Thus, what is needed for this script to run is enough to run your method too. 

After studying the preprocessing script, I concluded it needs the following to run:

- A set of folders with RGB images per camera.
- A set of folders with a human mask per camera.
- A file 'annots.py' containing a 'cams' key. That contains K, R, T, D information for each cam.
- A folder 'new_params' containing a .npy file per pose which in turn contains 'poses', 'Rh', 'Th' and 'shapes' information.
- A 'body_models' folder that can be obtained with [these](https://github.com/mikeqzy/3dgs-avatar-release?tab=readme-ov-file#smpl-setup) instructions. 

Thus, if we are just given an RGB video and we want to run your method, we should 1) run a masking method to produce the human mask per frame, 2) run a method to give us intrinsic and extrinsic per camera (most probably COLMAP), 3) run a 3D human reconstruction method to get poses, shapes and Rh, Th per pose, and 4) format the data properly to run the preprocess script and then run your train.py file. 

Hopefully, that sums up the procedure correctly. I have two questions, though:
1) What is D and how do we obtain this?
2) How do we obtain 'poses', 'Rh', 'Th' and 'shapes' per pose? Does [SPIN](https://github.com/nkolot/SPIN) predict this information per pose?

Thank you for your work and time,
Agelos

**Comment by mikeqzy** [comment]
Hello, thank you for your interest in our work. Your conclusions are absolutely correct. Regarding your questions:
1. D is the camera distortion parameters provided by ZJUMoCap. Usually it's safe to set it to all zero.
2. These are basically the body pose, global orientation, translation and shape parameter, respectively. You can estimate SMPL pose and shape with any off-the-shelf methods, including SPIN for sure. 

Recently my colleague has provided a script for data processing on custom videos, please refer to https://github.com/mikeqzy/3dgs-avatar-release/issues/11#issuecomment-2308474585. Hope it helps!

**Comment by agelosk** [comment]
Thanks for your reply. The code provided by your colleague is indeed very useful. Few follow up questions:

1.  Any idea why on [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py), R is set to the identity matrix? I have COLMAP information per camera. Is it safe to set K directly from cameras.txt, `R = quaternion_to_matrix(qw,qx,qy,qz)` and `T = - R.T * [tx,ty,tz]` where qw,qx,qy,qz,tx,ty,tz are directly from images.txt.
2. I did try the above and the 3dgs-avatar is not able to be trained, i just get black rendered images, and at iteration 3000 i get an error `q1[0] = 1.  # [1,0,0,0] represents identity rotation. IndexError: index 0 is out of bounds for dimension 0 with size 0`

This is regarding the Neuman dataset. Obviously there is something wrong with my K,R,T inputs. When I am using [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) to initialize K,R,T the model does train but I get very poor results identifying that still something is wrong. Can you enlighten me with how I should initialize K,R,T from COLMAP?

![image](https://github.com/user-attachments/assets/e2e613f4-3329-43e8-a954-659998495405)

Appreciate your time,
Agelos

**Comment by mikeqzy** [comment]
1. I'm not familiar with mmhuman3d, but here's my guess: The smpl estimation should be aligned with camera calibration. For ZJUMoCap, the SMPL parameters are in the world coordinate and cameras are calibrated. For custom video, we have no ground-truth camera calibration. The SMPL estimate from [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) is in the camera space of each given camera, with a preset intrinsics, see [here](https://github.com/xiyichen/mmhuman3d/blob/main/docs/cameras.md). So the SMPL parameters from [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) are view-dependent and not consistent in the world coordinate, but they are aligned with the initialized camera (preset K, identity matrix R, zero T). With COLMAP camera estimate, you might need to do additional optimization to get consistent world-coordinate SMPL parameters.
2. The model enables the non-rigid deformation module at 3000 step, though I'm not sure why this error happens.

By using the default camera parameter from [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) I believe the model will behave normally on Neuman dataset. Hope it helps!

**Comment by 120829** [comment]
> Thanks for your reply. The code provided by your colleague is indeed very useful. Few follow up questions:感谢您的回复。你同事提供的代码确实很有用。几个后续问题：
> 
>     1. Any idea why on [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py), R is set to the identity matrix? I have COLMAP information per camera. Is it safe to set K directly from cameras.txt, `R = quaternion_to_matrix(qw,qx,qy,qz)` and `T = - R.T * [tx,ty,tz]` where qw,qx,qy,qz,tx,ty,tz are directly from images.txt.知道为什么在 [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) 上，R 被设置为单位矩阵吗？我有每台相机的 COLMAP 信息。直接从 cameras.txt 设置 K 是否安全， `R = quaternion_to_matrix(qw,qx,qy,qz)` `T = - R.T * [tx，ty，tz]` 其中 qw，qx，qy，qz，tx，ty，tz 直接来自 images.txt。
> 
>     2. I did try the above and the 3dgs-avatar is not able to be trained, i just get black rendered images, and at iteration 3000 i get an error `q1[0] = 1.  # [1,0,0,0] represents identity rotation. IndexError: index 0 is out of bounds for dimension 0 with size 0`我确实尝试了上述方法，但 3dgs-avatar 无法训练，我只得到了黑色渲染的图像，并且在迭代 3000 时我遇到了 `q1[0] = 1.  # [1,0,0,0] represents identity rotation. IndexError: index 0 is out of bounds for dimension 0 with size 0` 错误
> 
> 
> This is regarding the Neuman dataset. Obviously there is something wrong with my K,R,T inputs. When I am using [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) to initialize K,R,T the model does train but I get very poor results identifying that still something is wrong. Can you enlighten me with how I should initialize K,R,T from COLMAP?这是关于 Neuman 数据集的。显然，我的 K、R、T 输入有问题。当我使用 [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) 初始化 K，R，T 时，模型确实进行了训练，但我得到的结果非常糟糕，发现仍然有问题。您能告诉我如何从 COLMAP 初始化 K、R、T 吗？
> 
> ![image](https://private-user-images.githubusercontent.com/45033489/364118779-e2e613f4-3329-43e8-a954-659998495405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzIyMTAsIm5iZiI6MTcyNTkzMTkxMCwicGF0aCI6Ii80NTAzMzQ4OS8zNjQxMTg3NzktZTJlNjEzZjQtMzMyOS00M2U4LWE5NTQtNjU5OTk4NDk1NDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAxMzE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZjUyZmNlN2UyNDM5Y2IwM2JjZjJiNjZkNWI1ZGIzMzQwMGRkMTc0NDBhN2RmZmQwZjgwMmMxYWZiNDUwN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A95z1PpJAIc3xBSkGX51CQ5PZvHccWx-j7BnLvtN8mw)
> 
> Appreciate your time, 珍惜您的时间， Agelos 阿杰洛斯

The issue might be related to the pose_correction module. You could try disabling this module, but I’m not entirely sure about the exact cause. If you find the real reason, could you share it with me? Thanks in advance."

**Comment by alasokolova** [comment]
Hi @agelosk,
have you succeeded running the approach on your custom data?
