### ISSUE TITLE
identity rotation in non_rigid.py

### ISSUE THREAD

**Issue by xianrui-luo** [mikeqzy/3dgs-avatar-release#28]
Hi, in non_rigid.py ` q1[0] = 1.  # [1,0,0,0] represents identity rotation` but the shape is [x,4]
I wonder if the code should be q1[:,0]=1?

**Comment by mikeqzy** [comment]
You are right, this is indeed a bug. I fixed it in the latest commit. Testing on ZJUMoCap-377, the result is almost the same, so I assume this will not affect much. Thank you for your report!
