### ISSUE TITLE
Can’t find ‘3dgs-avatar-release/submodules/simple-knn’

### ISSUE THREAD

**Issue by XiaokunSun** [mikeqzy/3dgs-avatar-release#3]
Can’t find ‘3dgs-avatar-release/submodules/simple-knn’

**Comment by mikeqzy** [comment]
Hi,
Did you clone the submodule also by running `git submodule update --init --recursive`?

**Comment by XiaokunSun** [comment]
I ran the command, the problem is that the link (submodules/simple-knn) in your code seems to be disabled.
![QQ截图20240129192823](https://github.com/mikeqzy/3dgs-avatar-release/assets/47241760/c3647a31-d301-49b5-957c-9c399414b3c4)

**Comment by mikeqzy** [comment]
I checked the command and it works on my machine. The code repository is on [gitlab](https://gitlab.inria.fr/bkerbl/simple-knn) so you can't open it directly on github, but it should work with `git submodule update`

**Comment by XiaokunSun** [comment]
I understand, thanks for your reply.
