### ISSUE TITLE
'Undistort' for People Snapshot dataset

### ISSUE THREAD

**Issue by JuewenPeng** [mikeqzy/3dgs-avatar-release#30]
For People Snapshot dataset, I found that in InstantAvatar, they have performed 'undistort' to the image when extracting frames from the video. If I use that preprocessed dataset for training, do I need to 'undistort' the image again when loading the dataset, like what you did in https://github.com/mikeqzy/3dgs-avatar-release/blob/main/dataset/people_snapshot.py#L285C21-L285C30

**Comment by mikeqzy** [comment]
Hi, since we are processing the frames instead of raw video as in InstantAvatar, I believe they are not undistorted before.
