### ISSUE TITLE
About shape parameter

### ISSUE THREAD

**Issue by wyiguanw** [mikeqzy/3dgs-avatar-release#32]
thanks for the great work! I noticed that you manually calculate vertices from SMPL pose parameters. Did you use shape parameters? 
There is a 'minimal_shape' in 'get_cano_smpl_verts(self, data_path)' for the clothed shape, I am not sure if this is calculated for shape blend shape from 'v_shape & shape parameter'

**Comment by mikeqzy** [comment]
Good observation! You are right, `minimal_shape` includes shape blend shape.

**Comment by wyiguanw** [comment]
Thanks for the quick response! One more question. Are shape parameters updated while doing pose correction?

**Comment by mikeqzy** [comment]
Yes, shape parameters for the subject are also optimized, see [here](https://github.com/mikeqzy/3dgs-avatar-release/blob/fc39bc5ec622d1de33f38b4b9c6d39b8485bdecd/models/pose_correction/pose_correction.py#L188)
