### ISSUE TITLE
Issue while creating the conda environment

### ISSUE THREAD

**Issue by Gojo1729** [mikeqzy/3dgs-avatar-release#6]
Hello,
When I try to create the environment using the conda command I'm getting the following error - 
```
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple_knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed
```
For detailed error checkout this file
[issue.txt](https://github.com/mikeqzy/3dgs-avatar-release/files/14356223/issue.txt)

My system specifications
WSL Ubuntu 22.04
CUDA - 11.6, 
Python - 3.7.

**Comment by Gojo1729** [comment]
I think there is some issue with the ninja commad, I'm using ninja 1.10.1, when I use ninja -v I'm getting an error, which ninja version I'm suppose to use to build the binaries ?

**Comment by mikeqzy** [comment]
Hi,
ninja is not required to install the submodules.
It seems that the error is related to https://github.com/graphdeco-inria/gaussian-splatting/issues/535, https://github.com/graphdeco-inria/gaussian-splatting/issues/645. I hope the solutions in these threads work for you.

**Comment by Gojo1729** [comment]
@mikeqzy Thanks for the links, this https://github.com/graphdeco-inria/gaussian-splatting/issues/535#issuecomment-1872494333 worked for me
